project:  OpenStack Ansible Deployment Meeting
meeting_id: openstack_ansible_meeting
schedule:
  - time:       '1600'
    day:        Thursday
    irc:        openstack-meeting-4
    frequency:  weekly
chair: Kevin Carter (cloudnull)
description:  >
  OpenStack+Ansible
