project:  Win the Enterprise - Deployment Team
schedule:
  - time:       '1500'
    day:        Tuesday
    irc:        (nil) See description
    frequency:  weekly
chair:  Carol Barrett (Barrett)
description:  >
  Dial In: 1-503-264-2663, Bridge: 3; Pass Code: 7053780
